SRC_DIR = $(PWD)/../src

.PHONY: binary_to_bcd_tb clock_register_tb button_debounce_tb clk_gen_tb all clean

all: clk_gen_tb.vcd button_debounce_tb.vcd clock_register_tb.vcd binary_to_bcd_tb.vcd

binary_to_bcd_tb: binary_to_bcd_tb.vcd
	gtkwave -o $< $@.gtkw

clock_register_tb: clock_register_tb.vcd
	gtkwave -o $< $@.gtkw

button_debounce_tb: button_debounce_tb.vcd
	gtkwave -o $< $@.gtkw

clk_gen_tb: clk_gen_tb.vcd
	gtkwave -o $< $@.gtkw

binary_to_bcd_tb.vvp: binary_to_bcd_tb.v $(SRC_DIR)/binary_to_bcd.v
	iverilog -o $@ $^

clock_register_tb.vvp: clock_register_tb.v $(SRC_DIR)/clock_register.v $(SRC_DIR)/button_debounce.v $(SRC_DIR)/clk_gen.v
	iverilog -o $@ $^

button_debounce_tb.vvp: button_debounce_tb.v $(SRC_DIR)/button_debounce.v $(SRC_DIR)/clk_gen.v
	iverilog -o $@ $^

clk_gen_tb.vvp: clk_gen_tb.v $(SRC_DIR)/clk_gen.v
	iverilog -o $@ $^

%.vcd : %.vvp
	vvp $^

clean:
	-rm *.vcd
	-rm *.vvp
	-rm *.fst
