name: test
on: [push, workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install iverilog
        shell: bash
        run: sudo apt-get update && sudo apt-get install -y iverilog

      - name: Run tests
        run: |
          cd test
          make -f makefile.iverilog clean
          make -f makefile.iverilog
          # make will return success even if the test fails, so check for failure in the results.xml
          ! grep failure results.xml

      - name: Test Summary
        uses: test-summary/action@v2.3
        with:
          paths: "test/results.xml"
        if: always()

      - name: upload vcd
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: simulation traces
          path: |
            test/clk_gen_tb.vcd
            test/button_debounce_tb.vcd
            test/clock_register_tb.vcd
            test/binary_to_bcd_tb.vcd
            test/results.xml
